# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "POST_TAG" ("postId" INTEGER NOT NULL,"tagId" INTEGER NOT NULL);
alter table "POST_TAG" add constraint "pk_post_tag" primary key("postId","tagId");
create table "POST" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"title" VARCHAR NOT NULL,"author" VARCHAR NOT NULL,"content" VARCHAR NOT NULL);
create table "TAG" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"name" VARCHAR NOT NULL);
alter table "POST_TAG" add constraint "fk_post_tag_tagid" foreign key("tagId") references "TAG"("id") on update NO ACTION on delete NO ACTION;
alter table "POST_TAG" add constraint "fk_post_tag_postid" foreign key("postId") references "POST"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "POST_TAG" drop constraint "fk_post_tag_tagid";
alter table "POST_TAG" drop constraint "fk_post_tag_postid";
alter table "POST_TAG" drop constraint "pk_post_tag";
drop table "POST_TAG";
drop table "POST";
drop table "TAG";

